version: "3"
services:
  selenium:
    image: selenium/hub:3.141.59-20210929
    container_name: selenium
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20210929
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.141.59-20210929
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444